@startuml

title Agencia interactuando con Auto

"a: Agencia" -> ":Auto": alquilar(2)
":Auto" -> ":Auto": precioBase(2)
activate ":Auto"
":Auto" -> "c: CostoBase": multiplicar(2)
"c: CostoBase" --> ":Auto": 2 * 500

":Auto" -> "p: PlazasBasica": alquilar(4 /* plazas */)
"p: PlazasBasica" --> ":Auto": 4 * 100
deactivate ":Auto"

"a: Agencia" <-- ":Auto": [base] + [plazas]


@enduml