@startuml

title Agencia interactuando con Camion

"a: Agencia" -> ":Camion": alquilar(2)

activate ":Camion"
":Camion" -> "c: CostoBase": multiplicar(2)
"c: CostoBase" --> ":Camion": 2 * 1500

":Camion" -> ":Camion": precioPma()

deactivate ":Camion"

":Camion" --> "a: Agencia": [precioBase + precioPMA]

@enduml