@startuml

title testRegistroCherryQQElCostoDealquilarPor1DiaEs900

Actor Desarrollador

Desarrollador -> ":TestCase": run
create "a: Agencia"
":TestCase" -> "a: Agencia": Agencia()

create "p: PlazasBasica"
":TestCase" -> "p: PlazasBasica": PlazaBasica()

create "auto :Auto"
":TestCase" -> "auto :Auto": Auto(patente, 4, p)

":TestCase" -> "a: Agencia": registrar(auto)

"a: Agencia" -> "a: Agencia": encontrar(auto)
activate "a: Agencia"
loop Para cada vehiculo
    "a: Agencia" -> ":Auto": igualA(auto)
end
deactivate "a: Agencia"

":TestCase" -> "a: Agencia": alquilarDias("abc-123", 2)

"a: Agencia" -> "a: Agencia": encontrar(new Patente("abc-123"))
activate "a: Agencia"
loop Para cada vehiculo
    "a: Agencia" -> ":Vehiculo": tengoPatente(new Patente("abc-123"))
end
deactivate "a: Agencia"

"a: Agencia" -> "auto :Auto": alquilar(2)
note right: Este diagrama está en... \n ds_polimorfismo_agencia_interactuando_con_auto.plantuml

@enduml